<a href="https://colab.research.google.com/github/aishwarya071/covid_companion/blob/main/Final_Year.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from pandas import read_csv
from sklearn.decomposition import PCA

from sklearn.datasets import fetch_openml
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/COViDSTRESS.xlsx')

In [ ]:
df.shape

(125307, 152)

In [ ]:
new_header = df.iloc[0] #grab the first row for the header
df = df[1:] #take the data less the header row
df.columns = new_header #set the header row as the df header

In [ ]:
df.head(3)

,SRN,Duration..in.seconds.,UserLanguage,Dem_age,Dem_gender,Dem_edu,Dem_edu_mom,Dem_employment,Country,Dem_Expat,...,Final_open,PSS10_avg,SLON3_avg,neu,ext,ope,agr,con,SPS_avg,Scale_UCLA_TRI_avg
1,1,180,SAR,29,Female,"College degree, bachelor, master",Some College or equivalent,Not employed,Argentina,yes,...,0,2.9,3,0,0,0,0,0,0,0
2,2,3100,UR,20,Male,"College degree, bachelor, master",None,Student,Pakistan,yes,...,0,2.2,2.333333,2,5,5.333333,5,5,5,0
3,3,127,SAR,47,Female,"Some College, short continuing education or eq...",Some College or equivalent,Self-employed,Argentina,no,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
list(df.columns)

['SRN',
 'Duration..in.seconds.',
 'UserLanguage',
 'Dem_age',
 'Dem_gender',
 'Dem_edu',
 'Dem_edu_mom',
 'Dem_employment',
 'Country',
 'Dem_Expat',
 'Dem_state',
 'Dem_maritalstatus',
 'Dem_dependents',
 'Dem_riskgroup',
 'Dem_islolation',
 'Dem_isolation_adults',
 'Dem_isolation_kids',
 'AD_gain',
 'AD_loss',
 'AD_check',
 'Scale_PSS10_UCLA_1',
 'Scale_PSS10_UCLA_2',
 'Scale_PSS10_UCLA_3',
 'Scale_PSS10_UCLA_4',
 'Scale_PSS10_UCLA_5',
 'Scale_PSS10_UCLA_6',
 'Scale_PSS10_UCLA_7',
 'Scale_PSS10_UCLA_8',
 'Scale_PSS10_UCLA_9',
 'Scale_PSS10_UCLA_10',
 'Scale_SLON_1',
 'Scale_SLON_2',
 'Scale_SLON_3',
 'OECD_people_1',
 'OECD_people_2',
 'OECD_insititutions_1',
 'OECD_insititutions_2',
 'OECD_insititutions_3',
 'OECD_insititutions_4',
 'OECD_insititutions_5',
 'OECD_insititutions_6',
 'Corona_concerns_1',
 'Corona_concerns_2',
 'Corona_concerns_3',
 'Corona_concerns_4',
 'Corona_concerns_5',
 'Trust_countrymeasure',
 'Compliance_1',
 'Compliance_2',
 'Compliance_3',
 'Compliance_4',
 'Compliance_5',
 'Compliance_6',
 'born_92',
 'experience_war',
 'experience_war_TXT',
 'war_injury',
 'loss_during_war',
 'time_spent_in_war',
 'time_spent_in_war_TXT',
 'Scale_UCLA_TRI_1',
 'Scale_UCLA_TRI_2',
 'Scale_UCLA_TRI_3',
 'Scale_UCLA_TRI_4',
 'PS_PTSD_1',
 'PS_PTSD_2',
 'PS_PTSD_3',
 'PS_PTSD_4',
 'PS_PTSD_5',
 'BFF_15_1',
 'BFF_15_2',
 'BFF_15_3',
 'BFF_15_4',
 'BFF_15_5',
 'BFF_15_6',
 'BFF_15_7',
 'BFF_15_8',
 'BFF_15_9',
 'BFF_15_10',
 'BFF_15_11',
 'BFF_15_12',
 'BFF_15_13',
 'BFF_15_14',
 'BFF_15_15',
 'Expl_Distress_1',
 'Expl_Distress_2',
 'Expl_Distress_3',
 'Expl_Distress_4',
 'Expl_Distress_5',
 'Expl_Distress_6',
 'Expl_Distress_7',
 'Expl_Distress_8',
 'Expl_Distress_9',
 'Expl_Distress_10',
 'Expl_Distress_11',
 'Expl_Distress_12',
 'Expl_Distress_13',
 'Expl_Distress_14',
 'Expl_Distress_15',
 'Expl_Distress_16',
 'Expl_Distress_17',
 'Expl_Distress_18',
 'Expl_Distress_19',
 'Expl_Distress_20',
 'Expl_Distress_21',
 'Expl_Distress_22',
 'Expl_Distress_23',
 'Expl_Distress_24',
 'Expl_Distress_txt',
 'SPS_1',
 'SPS_2',
 'SPS_3',
 'SPS_4',
 'SPS_5',
 'SPS_6',
 'SPS_7',
 'SPS_8',
 'SPS_9',
 'SPS_10',
 'Expl_Coping_1',
 'Expl_Coping_2',
 'Expl_Coping_3',
 'Expl_Coping_4',
 'Expl_Coping_5',
 'Expl_Coping_6',
 'Expl_Coping_7',
 'Expl_Coping_8',
 'Expl_Coping_9',
 'Expl_Coping_10',
 'Expl_Coping_11',
 'Expl_Coping_12',
 'Expl_Coping_13',
 'Expl_Coping_14',
 'Expl_Coping_15',
 'Expl_Coping_16',
 'Expl_coping_txt',
 'Expl_media_1',
 'Expl_media_2',
 'Expl_media_3',
 'Expl_media_4',
 'Expl_media_5',
 'Expl_media_6',
 'Final_open',
 'PSS10_avg',
 'SLON3_avg',
 'neu',
 'ext',
 'ope',
 'agr',
 'con',
 'SPS_avg',
 'Scale_UCLA_TRI_avg']

In [ ]:
df.drop(labels=['SRN','Duration..in.seconds.','UserLanguage','neu','ext','ope','agr','con','AD_gain','AD_loss','AD_check','born_92','experience_war',
 'experience_war_TXT','war_injury','loss_during_war','time_spent_in_war','time_spent_in_war_TXT','Scale_UCLA_TRI_1','Scale_UCLA_TRI_2','Scale_UCLA_TRI_3',
 'Scale_UCLA_TRI_4','PS_PTSD_1','PS_PTSD_2','PS_PTSD_3','PS_PTSD_4','PS_PTSD_5','Final_open','Scale_UCLA_TRI_avg'], axis = 1,inplace=True)

In [ ]:
df['OECD_people_avg'] = df[['OECD_people_1', 'OECD_people_2']].mean(axis=1)

df['OECD_insititution_avg'] = df[['OECD_insititutions_1', 'OECD_insititutions_2', 'OECD_insititutions_3', 'OECD_insititutions_4', 'OECD_insititutions_5',
 'OECD_insititutions_6']].mean(axis=1)

df['Corona_concerns_avg'] = df[['Corona_concerns_1', 'Corona_concerns_2', 'Corona_concerns_3', 'Corona_concerns_4', 'Corona_concerns_5']].mean(axis=1) 

df['Expl_Distress_avg']=df[['Expl_Distress_1','Expl_Distress_2','Expl_Distress_3','Expl_Distress_4','Expl_Distress_5','Expl_Distress_6','Expl_Distress_7','Expl_Distress_8','Expl_Distress_9','Expl_Distress_10','Expl_Distress_11','Expl_Distress_12','Expl_Distress_13','Expl_Distress_14','Expl_Distress_15','Expl_Distress_16','Expl_Distress_17','Expl_Distress_18','Expl_Distress_19','Expl_Distress_20','Expl_Distress_21','Expl_Distress_22','Expl_Distress_23','Expl_Distress_24']].mean(axis=1)

In [ ]:
df.head(2)

,Dem_age,Dem_gender,Dem_edu,Dem_edu_mom,Dem_employment,Country,Dem_Expat,Dem_state,Dem_maritalstatus,Dem_dependents,...,Expl_media_4,Expl_media_5,Expl_media_6,PSS10_avg,SLON3_avg,SPS_avg,OECD_people_avg,OECD_insititution_avg,Corona_concerns_avg,Expl_Distress_avg
1,29,Female,"College degree, bachelor, master",Some College or equivalent,Not employed,Argentina,yes,TucumÃ¡n,Single,0,...,0,0,0,2.9,3,0,0.0,0.0,0.0,0.000000
2,20,Male,"College degree, bachelor, master",None,Student,Pakistan,yes,<U+0622><U+0632><U+0627><U+062F> <U+06A9><U+06...,Single,0,...,4,2,3,2.2,2.333333,5,6.5,4.0,3.2,27.583333

In [ ]:
df['Compliance_avg'] = df[['Compliance_1', 'Compliance_2', 'Compliance_3', 'Compliance_4', 'Compliance_5', 'Compliance_6']].mean(axis=1)
df['Expl_media_avg'] = df[['Expl_media_1', 'Expl_media_2', 'Expl_media_3', 'Expl_media_4', 'Expl_media_5', 'Expl_media_6']].mean(axis=1)

In [ ]:
df.drop(labels=['Expl_Coping_1', 'Expl_Coping_2', 'Expl_Coping_3', 'Expl_Coping_4', 'Expl_Coping_5', 'Expl_Coping_6', 'Expl_Coping_7', 'Expl_Coping_8',
 'Expl_Coping_9', 'Expl_Coping_10', 'Expl_Coping_11', 'Expl_Coping_12', 'Expl_Coping_13', 'Expl_Coping_14', 'Expl_Coping_15', 'Expl_Coping_16', 'Expl_coping_txt', 'Expl_Distress_1', 'Expl_Distress_2', 'Expl_Distress_3', 'Expl_Distress_4', 'Expl_Distress_5', 'Expl_Distress_6', 'Expl_Distress_7', 'Expl_Distress_8',
 'Expl_Distress_9', 'Expl_Distress_10', 'Expl_Distress_11', 'Expl_Distress_12', 'Expl_Distress_13', 'Expl_Distress_14', 'Expl_Distress_15', 'Expl_Distress_16',
 'Expl_Distress_17', 'Expl_Distress_18', 'Expl_Distress_19', 'Expl_Distress_20', 'Expl_Distress_21', 'Expl_Distress_22', 'Expl_Distress_23', 'Expl_Distress_24',
 'Expl_Distress_txt', 'SPS_1', 'SPS_2', 'SPS_3', 'SPS_4', 'SPS_5', 'SPS_6', 'SPS_7', 'SPS_8', 'SPS_9', 'SPS_10','Scale_PSS10_UCLA_1', 'Scale_PSS10_UCLA_2',
 'Scale_PSS10_UCLA_3', 'Scale_PSS10_UCLA_4', 'Scale_PSS10_UCLA_5', 'Scale_PSS10_UCLA_6', 'Scale_PSS10_UCLA_7', 'Scale_PSS10_UCLA_8', 'Scale_PSS10_UCLA_9',
 'Scale_PSS10_UCLA_10', 'Scale_SLON_1', 'Scale_SLON_2', 'Scale_SLON_3', 'OECD_people_1', 'OECD_people_2', 'OECD_insititutions_1', 'OECD_insititutions_2',
 'OECD_insititutions_3', 'OECD_insititutions_4', 'OECD_insititutions_5', 'OECD_insititutions_6', 'Corona_concerns_1', 'Corona_concerns_2', 'Corona_concerns_3',
 'Corona_concerns_4', 'Corona_concerns_5','Compliance_1', 'Compliance_2', 'Compliance_3', 'Compliance_4', 'Compliance_avg','Compliance_5', 'Compliance_6','Expl_media_1', 'Expl_media_2', 'Expl_media_3', 'Expl_media_4', 'Expl_media_5', 'Expl_media_6'], axis = 1,inplace=True)

In [ ]:
list(df.columns)

['Dem_age',
 'Dem_gender',
 'Dem_edu',
 'Dem_edu_mom',
 'Dem_employment',
 'Country',
 'Dem_Expat',
 'Dem_state',
 'Dem_maritalstatus',
 'Dem_dependents',
 'Dem_riskgroup',
 'Dem_islolation',
 'Dem_isolation_adults',
 'Dem_isolation_kids',
 'Trust_countrymeasure',
 'BFF_15_1',
 'BFF_15_2',
 'BFF_15_3',
 'BFF_15_4',
 'BFF_15_5',
 'BFF_15_6',
 'BFF_15_7',
 'BFF_15_8',
 'BFF_15_9',
 'BFF_15_10',
 'BFF_15_11',
 'BFF_15_12',
 'BFF_15_13',
 'BFF_15_14',
 'BFF_15_15',
 'PSS10_avg',
 'SLON3_avg',
 'SPS_avg',
 'OECD_people_avg',
 'OECD_insititution_avg',
 'Corona_concerns_avg',
 'Expl_Distress_avg',
 'Expl_media_avg']

In [ ]:
df

,Dem_age,Dem_gender,Dem_edu,Dem_edu_mom,Dem_employment,Country,Dem_Expat,Dem_state,Dem_maritalstatus,Dem_dependents,...,BFF_15_14,BFF_15_15,PSS10_avg,SLON3_avg,SPS_avg,OECD_people_avg,OECD_insititution_avg,Corona_concerns_avg,Expl_Distress_avg,Expl_media_avg
1,29,Female,"College degree, bachelor, master",Some College or equivalent,Not employed,Argentina,yes,TucumÃ¡n,Single,0,...,0,0,2.9,3,0,0.0,0.000000,0.0,0.000000,0.000000
2,20,Male,"College degree, bachelor, master",None,Student,Pakistan,yes,<U+0622><U+0632><U+0627><U+062F> <U+06A9><U+06...,Single,0,...,2,5,2.2,2.333333,5,6.5,4.000000,3.2,27.583333,2.500000
3,47,Female,"Some College, short continuing education or eq...",Some College or equivalent,Self-employed,Argentina,no,CÃ³rdoba,Single,0,...,0,0,0,0,0,0.0,0.000000,0.0,0.000000,0.000000
4,79,Male,"College degree, bachelor, master",College degree,Not employed,Bulgaria,no,Lovech,Divorced/widowed,0,...,2,5,3.6,4,3.9,6.0,2.166667,0.6,26.708333,3.833333
5,61,Female,"Some College, short continuing education or eq...",Up to 12 years of school,Retired,Argentina,no,Mendoza,Married/cohabiting,0,...,2,4,2.714286,1,5,8.0,7.666667,3.4,8.541667,4.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125302,57,Male,Up to 12 years of school,None,Full time employed,Denmark,yes,Kolding,Single,1,...,2,6,1.4,1.333333,0,9.0,7.666667,3.4,10.208333,0.000000
125303,52,Female,"Some College, short continuing education or eq...",Some College or equivalent,Full time employed,Denmark,yes,Skanderborg,Single,0,...,3,4,3,3,4.3,8.0,8.500000,5.0,39.625000,4.333333
125304,29,Female,"College degree, bachelor, master",Some College or equivalent,Full time employed,Denmark,yes,0,Married/cohabiting,0,...,0,0,0,0,0,0.0,0.000000,0.0,0.000000,0.000000
125305,54,Male,"Some College, short continuing education or eq...",Some College or equivalent,Full time employed,Denmark,yes,KÃ¸benhavn,Married/cohabiting,0,...,4,4,1.9,1.666667,4.9,8.0,7.000000,3.2,14.333333,2.500000
125306,57,Female,Up to 12 years of school,Up to 12 years of school,Retired,Denmark,yes,0,Single,0,...,3,4,3.6,4.333333,3.555556,5.0,3.500000,5.4,36.833333,3.500000

In [ ]:
for i in range(1,len(df["BFF_15_3"])+1):
  if df["BFF_15_3"][i]==0:
    continue
  else:
    df["BFF_15_3"][i]=8-df["BFF_15_3"][i]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
for i in range(1,len(df["BFF_15_6"])+1):
  if df["BFF_15_6"][i]==0:
    continue
  else:
    df["BFF_15_6"][i]=8-df["BFF_15_6"][i]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
for i in range(1,len(df["BFF_15_10"])+1):
  if df["BFF_15_10"][i]==0:
    continue
  else:
    df["BFF_15_10"][i]=8-df["BFF_15_10"][i]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
for i in range(1,len(df["BFF_15_14"])+1):
  if df["BFF_15_14"][i]==0:
    continue
  else:
    df["BFF_15_14"][i]=8-df["BFF_15_14"][i]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
df['openness'] = df[['BFF_15_7', 'BFF_15_8', 'BFF_15_9']].mean(axis=1)
df['conscientiousness'] = df[['BFF_15_13', 'BFF_15_14', 'BFF_15_15']].mean(axis=1)
df['extroversion'] = df[['BFF_15_4', 'BFF_15_5', 'BFF_15_6']].mean(axis=1)
df['agreeableness'] = df[['BFF_15_10', 'BFF_15_11', 'BFF_15_12']].mean(axis=1)
df['neuroticism'] = df[['BFF_15_1', 'BFF_15_2', 'BFF_15_3']].mean(axis=1)

In [ ]:
df.drop(labels=['BFF_15_1',
 'BFF_15_2',
 'BFF_15_3',
 'BFF_15_4',
 'BFF_15_5',
 'BFF_15_6',
 'BFF_15_7',
 'BFF_15_8',
 'BFF_15_9',
 'BFF_15_10',
 'BFF_15_11',
 'BFF_15_12',
 'BFF_15_13',
 'BFF_15_14',
 'BFF_15_15'], axis = 1,inplace=True)

In [ ]:
for i in range(1,len(df["PSS10_avg"])+1):
  if df["PSS10_avg"][i]==0:
    continue
  else:
    df["PSS10_avg"][i]=6-df["PSS10_avg"][i]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
for i in range(1,len(df["SLON3_avg"])+1):
  if df["SLON3_avg"][i]==0:
    continue
  else:
    df["SLON3_avg"][i]=6-df["SLON3_avg"][i]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
for i in range(1,len(df["Corona_concerns_avg"])+1):
  if df["Corona_concerns_avg"][i]==0:
    continue
  else:
    df["Corona_concerns_avg"][i]=7-df["Corona_concerns_avg"][i]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
for i in range(1,len(df["Expl_Distress_avg"])+1):
  if df["Expl_Distress_avg"][i]==0:
    continue
  else:
    df["Expl_Distress_avg"][i]=8-df["Expl_Distress_avg"][i]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
for i in range(1,len(df["Expl_media_avg"])+1):
  if df["Expl_media_avg"][i]==0:
    continue
  else:
    df["Expl_media_avg"][i]=7-df["Expl_media_avg"][i]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
for i in range(1,len(df["extroversion"])+1):
  if df["extroversion"][i]==0:
    continue
  else:
    df["extroversion"][i]=8-df["extroversion"][i]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
for i in range(1,len(df["neuroticism"])+1):
  if df["neuroticism"][i]==0:
    continue
  else:
    df["neuroticism"][i]=8-df["neuroticism"][i]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
df

,Dem_age,Dem_gender,Dem_edu,Dem_edu_mom,Dem_employment,Country,Dem_Expat,Dem_state,Dem_maritalstatus,Dem_dependents,...,OECD_people_avg,OECD_insititution_avg,Corona_concerns_avg,Expl_Distress_avg,Expl_media_avg,openness,conscientiousness,extroversion,agreeableness,neuroticism
1,29,Female,"College degree, bachelor, master",Some College or equivalent,Not employed,Argentina,yes,TucumÃ¡n,Single,0,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,20,Male,"College degree, bachelor, master",None,Student,Pakistan,yes,<U+0622><U+0632><U+0627><U+062F> <U+06A9><U+06...,Single,0,...,6.5,4.000000,3.8,-19.583333,4.500000,5.333333,5.333333,2.666667,5.333333,5.666667
3,47,Female,"Some College, short continuing education or eq...",Some College or equivalent,Self-employed,Argentina,no,CÃ³rdoba,Single,0,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,79,Male,"College degree, bachelor, master",College degree,Not employed,Bulgaria,no,Lovech,Divorced/widowed,0,...,6.0,2.166667,6.4,-18.708333,3.166667,4.000000,5.333333,3.000000,5.333333,5.000000
5,61,Female,"Some College, short continuing education or eq...",Up to 12 years of school,Retired,Argentina,no,Mendoza,Married/cohabiting,0,...,8.0,7.666667,3.6,-0.541667,2.666667,5.333333,5.000000,3.000000,5.333333,4.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125302,57,Male,Up to 12 years of school,None,Full time employed,Denmark,yes,Kolding,Single,1,...,9.0,7.666667,3.6,-2.208333,0.000000,3.333333,6.000000,5.333333,5.666667,6.666667
125303,52,Female,"Some College, short continuing education or eq...",Some College or equivalent,Full time employed,Denmark,yes,Skanderborg,Single,0,...,8.0,8.500000,2.0,-31.625000,2.666667,5.000000,5.000000,4.000000,4.000000,3.000000
125304,29,Female,"College degree, bachelor, master",Some College or equivalent,Full time employed,Denmark,yes,0,Married/cohabiting,0,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
125305,54,Male,"Some College, short continuing education or eq...",Some College or equivalent,Full time employed,Denmark,yes,KÃ¸benhavn,Married/cohabiting,0,...,8.0,7.000000,3.8,-6.333333,4.500000,4.333333,4.333333,5.000000,3.333333,3.666667
125306,57,Female,Up to 12 years of school,Up to 12 years of school,Retired,Denmark,yes,0,Single,0,...,5.0,3.500000,1.6,-28.833333,3.500000,5.333333,4.000000,4.000000,4.000000,3.333333

In [ ]:
array = df.values

In [ ]:
list(df.columns)

['Dem_age',
 'Dem_gender',
 'Dem_edu',
 'Dem_edu_mom',
 'Dem_employment',
 'Country',
 'Dem_Expat',
 'Dem_state',
 'Dem_maritalstatus',
 'Dem_dependents',
 'Dem_riskgroup',
 'Dem_islolation',
 'Dem_isolation_adults',
 'Dem_isolation_kids',
 'Trust_countrymeasure',
 'PSS10_avg',
 'SLON3_avg',
 'SPS_avg',
 'OECD_people_avg',
 'OECD_insititution_avg',
 'Corona_concerns_avg',
 'Expl_Distress_avg',
 'Expl_media_avg',
 'openness',
 'conscientiousness',
 'extroversion',
 'agreeableness',
 'neuroticism']

In [ ]:
X = array[:,14:]

In [ ]:
X

array([[0, 3.1, 3, ..., 0.0, 0.0, 0.0],
       [5, 3.8, 3.666666667, ..., 2.666666666666667, 5.333333333333333,
        5.666666666666666],
       [0, 0, 0, ..., 0.0, 0.0, 0.0],
       ...,
       [0, 0, 0, ..., 0.0, 0.0, 0.0],
       [8, 4.1, 4.333333333, ..., 5.0, 3.3333333333333335,
        3.666666666666667],
       [10, 2.4, 1.6666666670000003, ..., 4.0, 4.0, 3.333333333333333]],
      dtype=object)

In [ ]:
import numpy as np

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit on training set only.
scaler.fit(X)
# Apply transform to both the training set and the test set.
X= scaler.transform(X)

In [ ]:
X

array([[-1.53767501, -0.01846703, -0.13331082, ..., -1.95326933,
        -2.27536047, -2.10766619],
       [ 0.35135107,  0.60179383,  0.37168163, ..., -0.33916871,
         0.67929124,  1.07507626],
       [-1.53767501, -2.76533652, -2.4057768 , ..., -1.95326933,
        -2.27536047, -2.10766619],
       ...,
       [-1.53767501, -2.76533652, -2.4057768 , ..., -1.95326933,
        -2.27536047, -2.10766619],
       [ 1.48476672,  0.86761991,  0.87667407, ...,  1.07316933,
        -0.42870315, -0.0482446 ],
       [ 2.24037716, -0.63872788, -1.1432957 , ...,  0.4678816 ,
        -0.05937169, -0.23546475]])

In [ ]:
pca = PCA(n_components=1)
principalComponents = pca.fit_transform(X)

In [ ]:
principalComponents = np.insert(principalComponents, 0, 0, axis=0)

In [ ]:
principalComponents

array([[ 0.        ],
       [ 6.09019183],
       [-2.09528443],
       ...,
       [ 7.38715245],
       [-2.18300872],
       [-0.21492255]])

In [ ]:
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['Mental_Health_Score'])

In [ ]:
finalDf = pd.concat([principalDf, df], axis = 1)

In [ ]:
finalDf = finalDf.drop(labels=0, axis=0)

In [ ]:
finalDf

,Mental_Health_Score,Dem_age,Dem_gender,Dem_edu,Dem_edu_mom,Dem_employment,Country,Dem_Expat,Dem_state,Dem_maritalstatus,...,OECD_people_avg,OECD_insititution_avg,Corona_concerns_avg,Expl_Distress_avg,Expl_media_avg,openness,conscientiousness,extroversion,agreeableness,neuroticism
1,6.090192,29,Female,"College degree, bachelor, master",Some College or equivalent,Not employed,Argentina,yes,TucumÃ¡n,Single,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,-2.095284,20,Male,"College degree, bachelor, master",None,Student,Pakistan,yes,<U+0622><U+0632><U+0627><U+062F> <U+06A9><U+06...,Single,...,6.5,4.000000,3.8,-19.583333,4.500000,5.333333,5.333333,2.666667,5.333333,5.666667
3,7.387152,47,Female,"Some College, short continuing education or eq...",Some College or equivalent,Self-employed,Argentina,no,CÃ³rdoba,Single,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,-1.073396,79,Male,"College degree, bachelor, master",College degree,Not employed,Bulgaria,no,Lovech,Divorced/widowed,...,6.0,2.166667,6.4,-18.708333,3.166667,4.000000,5.333333,3.000000,5.333333,5.000000
5,-2.002819,61,Female,"Some College, short continuing education or eq...",Up to 12 years of school,Retired,Argentina,no,Mendoza,Married/cohabiting,...,8.0,7.666667,3.6,-0.541667,2.666667,5.333333,5.000000,3.000000,5.333333,4.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125302,-2.032091,57,Male,Up to 12 years of school,None,Full time employed,Denmark,yes,Kolding,Single,...,9.0,7.666667,3.6,-2.208333,0.000000,3.333333,6.000000,5.333333,5.666667,6.666667
125303,-1.045055,52,Female,"Some College, short continuing education or eq...",Some College or equivalent,Full time employed,Denmark,yes,Skanderborg,Single,...,8.0,8.500000,2.0,-31.625000,2.666667,5.000000,5.000000,4.000000,4.000000,3.000000
125304,7.387152,29,Female,"College degree, bachelor, master",Some College or equivalent,Full time employed,Denmark,yes,0,Married/cohabiting,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
125305,-2.183009,54,Male,"Some College, short continuing education or eq...",Some College or equivalent,Full time employed,Denmark,yes,KÃ¸benhavn,Married/cohabiting,...,8.0,7.000000,3.8,-6.333333,4.500000,4.333333,4.333333,5.000000,3.333333,3.666667
125306,-0.214923,57,Female,Up to 12 years of school,Up to 12 years of school,Retired,Denmark,yes,0,Single,...,5.0,3.500000,1.6,-28.833333,3.500000,5.333333,4.000000,4.000000,4.000000,3.333333

In [ ]:
for i in finalDf.index:
    finalDf["Mental_Health_Score"][i]=finalDf["Mental_Health_Score"][i]+10

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
finalDf

,Mental_Health_Score,Dem_age,Dem_gender,Dem_edu,Dem_edu_mom,Dem_employment,Country,Dem_Expat,Dem_state,Dem_maritalstatus,...,OECD_people_avg,OECD_insititution_avg,Corona_concerns_avg,Expl_Distress_avg,Expl_media_avg,openness,conscientiousness,extroversion,agreeableness,neuroticism
1,16.090192,29,Female,"College degree, bachelor, master",Some College or equivalent,Not employed,Argentina,yes,TucumÃ¡n,Single,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,7.904716,20,Male,"College degree, bachelor, master",None,Student,Pakistan,yes,<U+0622><U+0632><U+0627><U+062F> <U+06A9><U+06...,Single,...,6.5,4.000000,3.8,-19.583333,4.500000,5.333333,5.333333,2.666667,5.333333,5.666667
3,17.387152,47,Female,"Some College, short continuing education or eq...",Some College or equivalent,Self-employed,Argentina,no,CÃ³rdoba,Single,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,8.926604,79,Male,"College degree, bachelor, master",College degree,Not employed,Bulgaria,no,Lovech,Divorced/widowed,...,6.0,2.166667,6.4,-18.708333,3.166667,4.000000,5.333333,3.000000,5.333333,5.000000
5,7.997181,61,Female,"Some College, short continuing education or eq...",Up to 12 years of school,Retired,Argentina,no,Mendoza,Married/cohabiting,...,8.0,7.666667,3.6,-0.541667,2.666667,5.333333,5.000000,3.000000,5.333333,4.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125302,7.967909,57,Male,Up to 12 years of school,None,Full time employed,Denmark,yes,Kolding,Single,...,9.0,7.666667,3.6,-2.208333,0.000000,3.333333,6.000000,5.333333,5.666667,6.666667
125303,8.954945,52,Female,"Some College, short continuing education or eq...",Some College or equivalent,Full time employed,Denmark,yes,Skanderborg,Single,...,8.0,8.500000,2.0,-31.625000,2.666667,5.000000,5.000000,4.000000,4.000000,3.000000
125304,17.387152,29,Female,"College degree, bachelor, master",Some College or equivalent,Full time employed,Denmark,yes,0,Married/cohabiting,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
125305,7.816991,54,Male,"Some College, short continuing education or eq...",Some College or equivalent,Full time employed,Denmark,yes,KÃ¸benhavn,Married/cohabiting,...,8.0,7.000000,3.8,-6.333333,4.500000,4.333333,4.333333,5.000000,3.333333,3.666667
125306,9.785077,57,Female,Up to 12 years of school,Up to 12 years of school,Retired,Denmark,yes,0,Single,...,5.0,3.500000,1.6,-28.833333,3.500000,5.333333,4.000000,4.000000,4.000000,3.333333

In [ ]:
list(finalDf.columns)

['Mental_Health_Score',
 'Dem_age',
 'Dem_gender',
 'Dem_edu',
 'Dem_edu_mom',
 'Dem_employment',
 'Country',
 'Dem_Expat',
 'Dem_state',
 'Dem_maritalstatus',
 'Dem_dependents',
 'Dem_riskgroup',
 'Dem_islolation',
 'Dem_isolation_adults',
 'Dem_isolation_kids',
 'Trust_countrymeasure',
 'PSS10_avg',
 'SLON3_avg',
 'SPS_avg',
 'OECD_people_avg',
 'OECD_insititution_avg',
 'Corona_concerns_avg',
 'Expl_Distress_avg',
 'Expl_media_avg',
 'openness',
 'conscientiousness',
 'extroversion',
 'agreeableness',
 'neuroticism']

In [ ]:
finalDf.drop(labels=['Dem_edu',
 'Dem_edu_mom','Dem_state','Dem_islolation'], axis = 1,inplace=True)

In [ ]:
finalDf['isolated_count'] = finalDf[['Dem_isolation_adults', 'Dem_isolation_kids']].sum(axis=1)

In [ ]:
finalDf.drop(labels=['Dem_isolation_adults', 'Dem_isolation_kids'], axis = 1,inplace=True)

In [ ]:
finalDf

,Mental_Health_Score,Dem_age,Dem_gender,Dem_employment,Country,Dem_Expat,Dem_maritalstatus,Dem_dependents,Dem_riskgroup,Trust_countrymeasure,...,OECD_insititution_avg,Corona_concerns_avg,Expl_Distress_avg,Expl_media_avg,openness,conscientiousness,extroversion,agreeableness,neuroticism,isolated_count
1,16.090192,29,Female,Not employed,Argentina,yes,Single,0,Yes,0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.0
2,7.904716,20,Male,Student,Pakistan,yes,Single,0,Yes,5,...,4.000000,3.8,-19.583333,4.500000,5.333333,5.333333,2.666667,5.333333,5.666667,0.0
3,17.387152,47,Female,Self-employed,Argentina,no,Single,0,No,0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
4,8.926604,79,Male,Not employed,Bulgaria,no,Divorced/widowed,0,Yes,5,...,2.166667,6.4,-18.708333,3.166667,4.000000,5.333333,3.000000,5.333333,5.000000,1.0
5,7.997181,61,Female,Retired,Argentina,no,Married/cohabiting,0,Yes,5,...,7.666667,3.6,-0.541667,2.666667,5.333333,5.000000,3.000000,5.333333,4.000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125302,7.967909,57,Male,Full time employed,Denmark,yes,Single,1,Yes,4,...,7.666667,3.6,-2.208333,0.000000,3.333333,6.000000,5.333333,5.666667,6.666667,2.0
125303,8.954945,52,Female,Full time employed,Denmark,yes,Single,0,0,4,...,8.500000,2.0,-31.625000,2.666667,5.000000,5.000000,4.000000,4.000000,3.000000,1.0
125304,17.387152,29,Female,Full time employed,Denmark,yes,Married/cohabiting,0,0,0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
125305,7.816991,54,Male,Full time employed,Denmark,yes,Married/cohabiting,0,Not sure,8,...,7.000000,3.8,-6.333333,4.500000,4.333333,4.333333,5.000000,3.333333,3.666667,0.0
125306,9.785077,57,Female,Retired,Denmark,yes,Single,0,Yes,10,...,3.500000,1.6,-28.833333,3.500000,5.333333,4.000000,4.000000,4.000000,3.333333,2.0

In [ ]:
finalDf["Dem_riskgroup"].replace(to_replace=0,value="Not sure", inplace=True)

In [ ]:
from collections import Counter

In [ ]:
Counter(finalDf["Dem_riskgroup"])

Counter({'No': 30491, 'Not sure': 10003, 'Yes': 84812})

In [ ]:
finalDf["Dem_employment"].replace(to_replace=0,value="Not employed", inplace=True)
finalDf["Dem_Expat"].replace(to_replace=0, value="no", inplace=True)
finalDf["Dem_maritalstatus"].replace(to_replace=0,value="Single", inplace=True)
finalDf["Dem_maritalstatus"].replace(to_replace="Uninformative response",value="Single", inplace=True)

In [ ]:
finalDf

,Mental_Health_Score,Dem_age,Dem_gender,Dem_employment,Country,Dem_Expat,Dem_maritalstatus,Dem_dependents,Dem_riskgroup,Trust_countrymeasure,...,OECD_insititution_avg,Corona_concerns_avg,Expl_Distress_avg,Expl_media_avg,openness,conscientiousness,extroversion,agreeableness,neuroticism,isolated_count
1,16.090192,29,Female,Not employed,Argentina,yes,Single,0,Yes,0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.0
2,7.904716,20,Male,Student,Pakistan,yes,Single,0,Yes,5,...,4.000000,3.8,-19.583333,4.500000,5.333333,5.333333,2.666667,5.333333,5.666667,0.0
3,17.387152,47,Female,Self-employed,Argentina,no,Single,0,No,0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
4,8.926604,79,Male,Not employed,Bulgaria,no,Divorced/widowed,0,Yes,5,...,2.166667,6.4,-18.708333,3.166667,4.000000,5.333333,3.000000,5.333333,5.000000,1.0
5,7.997181,61,Female,Retired,Argentina,no,Married/cohabiting,0,Yes,5,...,7.666667,3.6,-0.541667,2.666667,5.333333,5.000000,3.000000,5.333333,4.000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125302,7.967909,57,Male,Full time employed,Denmark,yes,Single,1,Yes,4,...,7.666667,3.6,-2.208333,0.000000,3.333333,6.000000,5.333333,5.666667,6.666667,2.0
125303,8.954945,52,Female,Full time employed,Denmark,yes,Single,0,Not sure,4,...,8.500000,2.0,-31.625000,2.666667,5.000000,5.000000,4.000000,4.000000,3.000000,1.0
125304,17.387152,29,Female,Full time employed,Denmark,yes,Married/cohabiting,0,Not sure,0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
125305,7.816991,54,Male,Full time employed,Denmark,yes,Married/cohabiting,0,Not sure,8,...,7.000000,3.8,-6.333333,4.500000,4.333333,4.333333,5.000000,3.333333,3.666667,0.0
125306,9.785077,57,Female,Retired,Denmark,yes,Single,0,Yes,10,...,3.500000,1.6,-28.833333,3.500000,5.333333,4.000000,4.000000,4.000000,3.333333,2.0

In [ ]:
finalDf=pd.get_dummies(finalDf, columns = ["Dem_gender"])
finalDf=pd.get_dummies(finalDf, columns = ["Dem_employment"])
finalDf=pd.get_dummies(finalDf, columns = ["Dem_Expat"])
finalDf=pd.get_dummies(finalDf, columns = ["Dem_maritalstatus"])
finalDf=pd.get_dummies(finalDf, columns = ["Dem_riskgroup"])

In [ ]:
list(finalDf.columns)

['Mental_Health_Score',
 'Dem_age',
 'Country',
 'Dem_dependents',
 'Trust_countrymeasure',
 'PSS10_avg',
 'SLON3_avg',
 'SPS_avg',
 'OECD_people_avg',
 'OECD_insititution_avg',
 'Corona_concerns_avg',
 'Expl_Distress_avg',
 'Expl_media_avg',
 'openness',
 'conscientiousness',
 'extroversion',
 'agreeableness',
 'neuroticism',
 'isolated_count',
 'Dem_gender_Female',
 'Dem_gender_Male',
 'Dem_gender_Other/would rather not say',
 'Dem_employment_Full time employed',
 'Dem_employment_Not employed',
 'Dem_employment_Part time employed',
 'Dem_employment_Retired',
 'Dem_employment_Self-employed',
 'Dem_employment_Student',
 'Dem_Expat_no',
 'Dem_Expat_yes',
 'Dem_maritalstatus_Divorced/widowed',
 'Dem_maritalstatus_Married/cohabiting',
 'Dem_maritalstatus_Other or would rather not say',
 'Dem_maritalstatus_Single',
 'Dem_riskgroup_No',
 'Dem_riskgroup_Not sure',
 'Dem_riskgroup_Yes']

In [ ]:
finalDf.drop(labels=['PSS10_avg',
 'SLON3_avg',
 'SPS_avg',
 'OECD_people_avg',
 'OECD_insititution_avg',
 'Corona_concerns_avg',
 'Expl_Distress_avg',
 'Expl_media_avg','Trust_countrymeasure'], axis = 1,inplace=True)

In [ ]:
len(list(finalDf.columns))

28

In [ ]:
gdpdf = pd.read_csv('/content/drive/MyDrive/gdp_csv.csv')

In [ ]:
gdpdf

      Country Name Country Code  Year         Value
0       Arab World          ARB  1968  2.576068e+10
1       Arab World          ARB  1969  2.843420e+10
2       Arab World          ARB  1970  3.138550e+10
3       Arab World          ARB  1971  3.642691e+10
4       Arab World          ARB  1972  4.331606e+10
...            ...          ...   ...           ...
11502     Zimbabwe          ZWE  2012  1.424249e+10
11503     Zimbabwe          ZWE  2013  1.545177e+10
11504     Zimbabwe          ZWE  2014  1.589105e+10
11505     Zimbabwe          ZWE  2015  1.630467e+10
11506     Zimbabwe          ZWE  2016  1.661996e+10

[11507 rows x 4 columns]

In [ ]:
for i in gdpdf.index:
  if gdpdf['Year'][i]==2016:
    continue
  else:
    gdpdf = gdpdf.drop(i)

In [ ]:
gdpdf

                         Country Name Country Code  Year         Value
48                         Arab World          ARB  2016  2.504703e+12
105            Caribbean small states          CSS  2016  6.670736e+10
132    Central Europe and the Baltics          CEB  2016  1.312158e+12
189        Early-demographic dividend          EAR  2016  1.040199e+13
246               East Asia & Pacific          EAS  2016  2.248043e+13
...                               ...          ...   ...           ...
11294                         Vietnam          VNM  2016  2.052762e+11
11365              West Bank and Gaza          PSE  2016  1.339710e+10
11392                     Yemen, Rep.          YEM  2016  2.731761e+10
11449                          Zambia          ZMB  2016  2.106399e+10
11506                        Zimbabwe          ZWE  2016  1.661996e+10

[236 rows x 4 columns]

In [ ]:
gdp=[]

for i in finalDf.index:
  flag=0
  for j in gdpdf.index:
    if finalDf['Country'][i] == gdpdf['Country Name'][j]:
      gdp.append(gdpdf["Value"][j])
      flag=1
      break
  if flag==0:
    gdp.append(0)

In [ ]:
gdp

[545476103427.247,
 278913371202.065,
 545476103427.247,
 53237882472.7108,
 545476103427.247,
 1858913163927.72,
 545476103427.247,
 545476103427.247,
 55187700000.0,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 55187700000.0,
 545476103427.247,
 55187700000.0,
 545476103427.247,
 1046922702460.87,
 55187700000.0,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 2465453975282.24,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 55187700000.0,
 545476103427.247,
 545476103427.247,
 53237882472.7108,
 55187700000.0,
 187592037839.968,
 18624475000000.0,
 55187700000.0,
 545476103427.247,
 53237882472.7108,
 53237882472.7108,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1858913163927.72,
 53237882472.7108,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 55187700000.0,
 55187700000.0,
 53237882472.7108,
 53237882472.7108,
 545476103427.247,
 55187700000.0,
 187592037839.968,
 238502900311.9,
 53237882472.7108,
 545476103427.247,
 55187700000.0,
 545476103427.247,
 53237882472.7108,
 545476103427.247,
 1046922702460.87,
 55187700000.0,
 53237882472.7108,
 238502900311.9,
 545476103427.247,
 238502900311.9,
 53237882472.7108,
 0,
 53237882472.7108,
 53237882472.7108,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 53237882472.7108,
 545476103427.247,
 1046922702460.87,
 53237882472.7108,
 53237882472.7108,
 0,
 53237882472.7108,
 545476103427.247,
 53237882472.7108,
 545476103427.247,
 2647898654635.24,
 545476103427.247,
 545476103427.247,
 16910277133.6463,
 53237882472.7108,
 306899653409.601,
 53237882472.7108,
 545476103427.247,
 53237882472.7108,
 53237882472.7108,
 11199145157649.2,
 545476103427.247,
 295456189492.005,
 187592037839.968,
 545476103427.247,
 53237882472.7108,
 2465453975282.24,
 545476103427.247,
 53237882472.7108,
 348743265704.561,
 16910277133.6463,
 3477796274496.8,
 514459972806.171,
 16910277133.6463,
 238502900311.9,
 238502900311.9,
 53237882472.7108,
 238502900311.9,
 238502900311.9,
 238502900311.9,
 238502900311.9,
 238502900311.9,
 238502900311.9,
 238502900311.9,
 238502900311.9,
 238502900311.9,
 238502900311.9,
 238502900311.9,
 238502900311.9,
 545476103427.247,
 238502900311.9,
 238502900311.9,
 306899653409.601,
 53237882472.7108,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 53237882472.7108,
 545476103427.247,
 545476103427.247,
 53237882472.7108,
 545476103427.247,
 545476103427.247,
 53237882472.7108,
 187592037839.968,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 304905406845.291,
 545476103427.247,
 53237882472.7108,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1204616439828.41,
 545476103427.247,
 53237882472.7108,
 0,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 238502900311.9,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 53237882472.7108,
 53237882472.7108,
 1858913163927.72,
 863711710426.514,
 53237882472.7108,
 545476103427.247,
 514459972806.171,
 53237882472.7108,
 187592037839.968,
 1046922702460.87,
 545476103427.247,
 53237882472.7108,
 514459972806.171,
 545476103427.247,
 53237882472.7108,
 53237882472.7108,
 53237882472.7108,
 545476103427.247,
 53237882472.7108,
 53237882472.7108,
 2647898654635.24,
 545476103427.247,
 1046922702460.87,
 53237882472.7108,
 53237882472.7108,
 1046922702460.87,
 53237882472.7108,
 53237882472.7108,
 53237882472.7108,
 53237882472.7108,
 1046922702460.87,
 1046922702460.87,
 23337907618.5174,
 1046922702460.87,
 545476103427.247,
 53237882472.7108,
 1858913163927.72,
 53237882472.7108,
 1046922702460.87,
 55187700000.0,
 53237882472.7108,
 514459972806.171,
 1046922702460.87,
 306899653409.601,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 53237882472.7108,
 545476103427.247,
 1858913163927.72,
 238502900311.9,
 545476103427.247,
 42738875963.3703,
 545476103427.247,
 53237882472.7108,
 1858913163927.72,
 53237882472.7108,
 1858913163927.72,
 53237882472.7108,
 1046922702460.87,
 1858913163927.72,
 53237882472.7108,
 1858913163927.72,
 1858913163927.72,
 1858913163927.72,
 53237882472.7108,
 187592037839.968,
 1046922702460.87,
 514459972806.171,
 1046922702460.87,
 187592037839.968,
 1858913163927.72,
 0,
 1046922702460.87,
 53237882472.7108,
 514459972806.171,
 238502900311.9,
 2465453975282.24,
 187592037839.968,
 1858913163927.72,
 53237882472.7108,
 238502900311.9,
 514459972806.171,
 1046922702460.87,
 187592037839.968,
 187592037839.968,
 1046922702460.87,
 53237882472.7108,
 42738875963.3703,
 545476103427.247,
 53237882472.7108,
 371076190476.19,
 187592037839.968,
 514459972806.171,
 53237882472.7108,
 53237882472.7108,
 1046922702460.87,
 42738875963.3703,
 2647898654635.24,
 42738875963.3703,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 53237882472.7108,
 42738875963.3703,
 545476103427.247,
 53237882472.7108,
 187592037839.968,
 53237882472.7108,
 1046922702460.87,
 238502900311.9,
 514459972806.171,
 545476103427.247,
 545476103427.247,
 1204616439828.41,
 1796186586414.45,
 187592037839.968,
 545476103427.247,
 53237882472.7108,
 187592037839.968,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 514459972806.171,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 55187700000.0,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 55187700000.0,
 545476103427.247,
 545476103427.247,
 55187700000.0,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 2647898654635.24,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 55187700000.0,
 1204616439828.41,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 2647898654635.24,
 1046922702460.87,
 514459972806.171,
 514459972806.171,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 2465453975282.24,
 514459972806.171,
 1046922702460.87,
 1046922702460.87,
 187592037839.968,
 55187700000.0,
 514459972806.171,
 55187700000.0,
 0,
 53237882472.7108,
 53237882472.7108,
 187592037839.968,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 55187700000.0,
 53237882472.7108,
 187592037839.968,
 1858913163927.72,
 1046922702460.87,
 514459972806.171,
 53237882472.7108,
 55187700000.0,
 2647898654635.24,
 1858913163927.72,
 53237882472.7108,
 53237882472.7108,
 187592037839.968,
 53237882472.7108,
 55187700000.0,
 545476103427.247,
 1046922702460.87,
 2647898654635.24,
 545476103427.247,
 2465453975282.24,
 514459972806.171,
 53237882472.7108,
 53237882472.7108,
 0,
 514459972806.171,
 514459972806.171,
 514459972806.171,
 514459972806.171,
 53237882472.7108,
 1046922702460.87,
 545476103427.247,
 53237882472.7108,
 1046922702460.87,
 187592037839.968,
 1046922702460.87,
 514459972806.171,
 514459972806.171,
 55187700000.0,
 1046922702460.87,
 545476103427.247,
 514459972806.171,
 55187700000.0,
 1046922702460.87,
 1046922702460.87,
 125816640420.569,
 1046922702460.87,
 1237255019653.86,
 545476103427.247,
 514459972806.171,
 1046922702460.87,
 53237882472.7108,
 55187700000.0,
 53237882472.7108,
 55187700000.0,
 55187700000.0,
 55187700000.0,
 55187700000.0,
 2647898654635.24,
 55187700000.0,
 371076190476.19,
 1046922702460.87,
 187592037839.968,
 55187700000.0,
 1046922702460.87,
 545476103427.247,
 55187700000.0,
 55187700000.0,
 55187700000.0,
 55187700000.0,
 55187700000.0,
 55187700000.0,
 55187700000.0,
 1046922702460.87,
 55187700000.0,
 1046922702460.87,
 1046922702460.87,
 187592037839.968,
 53237882472.7108,
 1046922702460.87,
 55187700000.0,
 1046922702460.87,
 514459972806.171,
 53237882472.7108,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 514459972806.171,
 55187700000.0,
 1046922702460.87,
 514459972806.171,
 1046922702460.87,
 1046922702460.87,
 53237882472.7108,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 55187700000.0,
 1046922702460.87,
 1046922702460.87,
 238502900311.9,
 55187700000.0,
 1046922702460.87,
 55187700000.0,
 1046922702460.87,
 1046922702460.87,
 1204616439828.41,
 1046922702460.87,
 514459972806.171,
 514459972806.171,
 53237882472.7108,
 514459972806.171,
 514459972806.171,
 1046922702460.87,
 1046922702460.87,
 2647898654635.24,
 55187700000.0,
 53237882472.7108,
 53237882472.7108,
 53237882472.7108,
 53237882472.7108,
 53237882472.7108,
 2647898654635.24,
 2647898654635.24,
 2647898654635.24,
 2647898654635.24,
 2647898654635.24,
 42738875963.3703,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 98613972000.0,
 545476103427.247,
 103606321692.582,
 187592037839.968,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 296535930381.12,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 53237882472.7108,
 0,
 1046922702460.87,
 53237882472.7108,
 545476103427.247,
 545476103427.247,
 53237882472.7108,
 777227541581.307,
 53237882472.7108,
 53237882472.7108,
 53237882472.7108,
 304819020500.641,
 545476103427.247,
 545476103427.247,
 53237882472.7108,
 53237882472.7108,
 53237882472.7108,
 390799991147.468,
 238502900311.9,
 32179069148.9362,
 53237882472.7108,
 42738875963.3703,
 53237882472.7108,
 1046922702460.87,
 238502900311.9,
 42738875963.3703,
 42738875963.3703,
 42738875963.3703,
 42738875963.3703,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 53237882472.7108,
 1046922702460.87,
 53237882472.7108,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 53237882472.7108,
 53237882472.7108,
 18624475000000.0,
 53237882472.7108,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 42738875963.3703,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1204616439828.41,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 53237882472.7108,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 103606321692.582,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 55187700000.0,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 55187700000.0,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 53237882472.7108,
 545476103427.247,
 2465453975282.24,
 1046922702460.87,
 53237882472.7108,
 53237882472.7108,
 1046922702460.87,
 1046922702460.87,
 53237882472.7108,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 68763255963.8943,
 0,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 0,
 53237882472.7108,
 0,
 545476103427.247,
 53237882472.7108,
 53237882472.7108,
 1046922702460.87,
 53237882472.7108,
 0,
 1046922702460.87,
 545476103427.247,
 53237882472.7108,
 1046922702460.87,
 1858913163927.72,
 2263792499341.01,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 863711710426.514,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1796186586414.45,
 53237882472.7108,
 1796186586414.45,
 1046922702460.87,
 53237882472.7108,
 1046922702460.87,
 1046922702460.87,
 53237882472.7108,
 1046922702460.87,
 16910277133.6463,
 53237882472.7108,
 545476103427.247,
 545476103427.247,
 238502900311.9,
 1046922702460.87,
 1858913163927.72,
 53237882472.7108,
 53237882472.7108,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 53237882472.7108,
 1046922702460.87,
 1046922702460.87,
 53237882472.7108,
 53237882472.7108,
 53237882472.7108,
 53237882472.7108,
 545476103427.247,
 53237882472.7108,
 1046922702460.87,
 1858913163927.72,
 53237882472.7108,
 53237882472.7108,
 238502900311.9,
 1046922702460.87,
 1046922702460.87,
 2465453975282.24,
 1046922702460.87,
 18624475000000.0,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 0,
 53237882472.7108,
 545476103427.247,
 1858913163927.72,
 1046922702460.87,
 53237882472.7108,
 1858913163927.72,
 53237882472.7108,
 0,
 545476103427.247,
 53237882472.7108,
 53237882472.7108,
 545476103427.247,
 1858913163927.72,
 1858913163927.72,
 1046922702460.87,
 1858913163927.72,
 1046922702460.87,
 42738875963.3703,
 53237882472.7108,
 3477796274496.8,
 42738875963.3703,
 1046922702460.87,
 1046922702460.87,
 53237882472.7108,
 53237882472.7108,
 1858913163927.72,
 1858913163927.72,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 53237882472.7108,
 53237882472.7108,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 18624475000000.0,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 863711710426.514,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1858913163927.72,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 204836597909.466,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 1858913163927.72,
 1046922702460.87,
 545476103427.247,
 545476103427.247,
 1046922702460.87,
 55187700000.0,
 1046922702460.87,
 1858913163927.72,
 1046922702460.87,
 545476103427.247,
 1858913163927.72,
 1858913163927.72,
 1858913163927.72,
 1046922702460.87,
 1858913163927.72,
 18624475000000.0,
 1858913163927.72,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 238502900311.9,
 1858913163927.72,
 1046922702460.87,
 1858913163927.72,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 545476103427.247,
 42738875963.3703,
 1858913163927.72,
 1858913163927.72,
 1046922702460.87,
 1046922702460.87,
 545476103427.247,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 1046922702460.87,
 187592037839.968,
 1046922702460.87,
 545476103427.247,
 42738875963.3703,
 1046922702460.87,
 1046922702460.87,
 1204616439828.41,
 1046922702460.87,
 42738875963.3703,
 545476103427.247,
 1046922702460.87,
 42738875963.3703,
 545476103427.247,
 1858913163927.72,
 1046922702460.87,
 238502900311.9,
 1046922702460.87,
 1858913163927.72,
 545476103427.247,
 0,
 1858913163927.72,
 545476103427.247,
 42738875963.3703,
 55187700000.0,
 187592037839.968,
 1858913163927.72,
 204836597909.466,
 1046922702460.87,
 1858913163927.72,
 545476103427.247,
 55187700000.0,
 1858913163927.72,
 545476103427.247,
 1858913163927.72,
 545476103427.247,
 545476103427.247,
 1858913163927.72,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 545476103427.247,
 1858913163927.72,
 545476103427.247,
 53237882472.7108,
 545476103427.247,
 545476103427.247,
 53237882472.7108,
 467955709817.539,
 53237882472.7108,
 545476103427.247,
 1858913163927.72,
 42738875963.3703,
 1858913163927.72,
 545476103427.247,
 42738875963.3703,
 0,
 1858913163927.72,
 0,
 50714957390.5378,
 1858913163927.72,
 53237882472.7108,
 238502900311.9,
 238502900311.9,
 0,
 238502900311.9,
 0,
 1858913163927.72,
 38299854688.1277,
 1858913163927.72,
 1858913163927.72,
 1858913163927.72,
 1858913163927.72,
 1858913163927.72,
 1858913163927.72,
 53237882472.7108,
 1858913163927.72,
 1858913163927.72,
 514459972806.171,
 204836597909.466,
 1858913163927.72,
 1858913163927.72,
 1858913163927.72,
 53237882472.7108,
 53237882472.7108,
 1858913163927.72,
 53237882472.7108,
 777227541581.307,
 53237882472.7108,
 1858913163927.72,
 1046922702460.87,
 1858913163927.72,
 42738875963.3703,
 1858913163927.72,
 16910277133.6463,
 1858913163927.72,
 0,
 38299854688.1277,
 545476103427.247,
 0,
 545476103427.247,
 38299854688.1277,
 38299854688.1277,
 238502900311.9,
 0,
 42738875963.3703,
 38299854688.1277,
 53237882472.7108,
 545476103427.247,
 545476103427.247,
 0,
 42738875963.3703,
 38299854688.1277,
 18624475000000.0,
 204836597909.466,
 1204616439828.41,
 2647898654635.24,
 ...]

In [ ]:
print(len(gdp))

125306

In [ ]:
finalDf['Gdp'] = gdp

In [ ]:
finalDf.head(100)

,Mental_Health_Score,Dem_age,Country,Dem_dependents,openness,conscientiousness,extroversion,agreeableness,neuroticism,isolated_count,...,Dem_Expat_no,Dem_Expat_yes,Dem_maritalstatus_Divorced/widowed,Dem_maritalstatus_Married/cohabiting,Dem_maritalstatus_Other or would rather not say,Dem_maritalstatus_Single,Dem_riskgroup_No,Dem_riskgroup_Not sure,Dem_riskgroup_Yes,Gdp
1,16.090192,29,Argentina,0,0.000000,0.000000,0.000000,0.000000,0.000000,4.0,...,0,1,0,0,0,1,0,0,1,5.454761e+11
2,7.904716,20,Pakistan,0,5.333333,5.333333,2.666667,5.333333,5.666667,0.0,...,0,1,0,0,0,1,0,0,1,2.789134e+11
3,17.387152,47,Argentina,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,1,0,0,0,0,1,1,0,0,5.454761e+11
4,8.926604,79,Bulgaria,0,4.000000,5.333333,3.000000,5.333333,5.000000,1.0,...,1,0,1,0,0,0,0,0,1,5.323788e+10
5,7.997181,61,Argentina,0,5.333333,5.000000,3.000000,5.333333,4.000000,1.0,...,1,0,0,1,0,0,0,0,1,5.454761e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,14.075801,23,China,0,0.000000,0.000000,0.000000,0.000000,0.000000,6.0,...,1,0,0,1,0,0,0,0,1,1.119915e+13
97,9.543880,52,Argentina,1,6.000000,4.666667,3.666667,6.333333,3.333333,0.0,...,1,0,0,0,0,1,1,0,0,5.454761e+11
98,17.387152,35,South Africa,0,0.000000,0.000000,0.000000,0.000000,0.000000,2.0,...,1,0,0,0,0,1,1,0,0,2.954562e+11
99,8.832209,31,Romania,0,3.666667,6.000000,5.000000,4.000000,4.666667,2.0,...,1,0,0,0,0,1,0,0,1,1.875920e+11
100,8.785260,37,Argentina,0,4.333333,4.666667,4.000000,5.666667,4.000000,0.0,...,1,0,0,0,0,1,0,0,1,5.454761e+11

In [ ]:
for i in finalDf.index:
  if finalDf['Country'][i]=="":
    finalDf = finalDf.drop(i)

In [ ]:
finalDf.drop(labels=['Country'], axis = 1,inplace=True)

In [ ]:
finalDf.head(100)

,Mental_Health_Score,Dem_age,Dem_dependents,openness,conscientiousness,extroversion,agreeableness,neuroticism,isolated_count,Dem_gender_Female,...,Dem_Expat_no,Dem_Expat_yes,Dem_maritalstatus_Divorced/widowed,Dem_maritalstatus_Married/cohabiting,Dem_maritalstatus_Other or would rather not say,Dem_maritalstatus_Single,Dem_riskgroup_No,Dem_riskgroup_Not sure,Dem_riskgroup_Yes,Gdp
1,16.090192,29,0,0.000000,0.000000,0.000000,0.000000,0.000000,4.0,1,...,0,1,0,0,0,1,0,0,1,5.454761e+11
2,7.904716,20,0,5.333333,5.333333,2.666667,5.333333,5.666667,0.0,0,...,0,1,0,0,0,1,0,0,1,2.789134e+11
3,17.387152,47,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1,...,1,0,0,0,0,1,1,0,0,5.454761e+11
4,8.926604,79,0,4.000000,5.333333,3.000000,5.333333,5.000000,1.0,0,...,1,0,1,0,0,0,0,0,1,5.323788e+10
5,7.997181,61,0,5.333333,5.000000,3.000000,5.333333,4.000000,1.0,1,...,1,0,0,1,0,0,0,0,1,5.454761e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,14.075801,23,0,0.000000,0.000000,0.000000,0.000000,0.000000,6.0,1,...,1,0,0,1,0,0,0,0,1,1.119915e+13
97,9.543880,52,1,6.000000,4.666667,3.666667,6.333333,3.333333,0.0,0,...,1,0,0,0,0,1,1,0,0,5.454761e+11
98,17.387152,35,0,0.000000,0.000000,0.000000,0.000000,0.000000,2.0,1,...,1,0,0,0,0,1,1,0,0,2.954562e+11
99,8.832209,31,0,3.666667,6.000000,5.000000,4.000000,4.666667,2.0,1,...,1,0,0,0,0,1,0,0,1,1.875920e+11
100,8.785260,37,0,4.333333,4.666667,4.000000,5.666667,4.000000,0.0,1,...,1,0,0,0,0,1,0,0,1,5.454761e+11

In [ ]:
finalDf.to_csv(r'\content\FinalPro.csv')

In [ ]:
len(list(finalDf.columns))

28

In [ ]:
list(finalDf.columns)

['Mental_Health_Score',
 'Dem_age',
 'Dem_dependents',
 'openness',
 'conscientiousness',
 'extroversion',
 'agreeableness',
 'neuroticism',
 'isolated_count',
 'Dem_gender_Female',
 'Dem_gender_Male',
 'Dem_gender_Other/would rather not say',
 'Dem_employment_Full time employed',
 'Dem_employment_Not employed',
 'Dem_employment_Part time employed',
 'Dem_employment_Retired',
 'Dem_employment_Self-employed',
 'Dem_employment_Student',
 'Dem_Expat_no',
 'Dem_Expat_yes',
 'Dem_maritalstatus_Divorced/widowed',
 'Dem_maritalstatus_Married/cohabiting',
 'Dem_maritalstatus_Other or would rather not say',
 'Dem_maritalstatus_Single',
 'Dem_riskgroup_No',
 'Dem_riskgroup_Not sure',
 'Dem_riskgroup_Yes',
 'Gdp']

In [ ]:
from pandas._libs.algos import unique_deltas
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# Install Tensorflow from the website: https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint

# Importing the dataset
dataset = finalDf
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, :1].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense( activation = 'relu', input_dim = 28, units=2000))

# Adding the second hidden layer
classifier.add(Dense(units = 1500, activation = 'relu'))

classifier.add(Dense(units = 1000, activation = 'relu'))

classifier.add(Dense(units = 500, activation = 'relu'))

classifier.add(Dense(units = 250, activation = 'relu'))

classifier.add(Dense(units = 150, activation = 'relu'))

classifier.add(Dense(units = 50, activation = 'relu'))

classifier.add(Dense(units = 25, activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, activation = 'relu'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'MeanSquaredError')

# Fitting the ANN to the Training set

es = EarlyStopping(monitor='loss', mode='min', verbose=1, patience=200)
mc = ModelCheckpoint('best_model.h5', monitor='loss', mode='min', verbose=1, save_best_only=True)
# fit model
history= classifier.fit(X_train, y_train, batch_size = 500, epochs = 500, callbacks=[es, mc])

# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results


# Making the Confusion Matrix

Epoch 1/500
201/201 [==============================] - ETA: 0s - loss: 4.0919
Epoch 1: loss improved from inf to 4.09187, saving model to best_model.h5
201/201 [==============================] - 68s 333ms/step - loss: 4.0919
Epoch 2/500
201/201 [==============================] - ETA: 0s - loss: 0.5001
Epoch 2: loss improved from 4.09187 to 0.50005, saving model to best_model.h5
201/201 [==============================] - 66s 331ms/step - loss: 0.5001
Epoch 3/500
201/201 [==============================] - ETA: 0s - loss: 0.4894
Epoch 3: loss improved from 0.50005 to 0.48940, saving model to best_model.h5
201/201 [==============================] - 66s 328ms/step - loss: 0.4894
Epoch 4/500
201/201 [==============================] - ETA: 0s - loss: 0.4825
Epoch 4: loss improved from 0.48940 to 0.48254, saving model to best_model.h5
201/201 [==============================] - 66s 328ms/step - loss: 0.4825
Epoch 5/500
201/201 [==============================] - ETA: 0s - loss: 0.4874
Epoch 5: loss did not improve from 0.48254
201/201 [==============================] - 66s 327ms/step - loss: 0.4874
Epoch 6/500
201/201 [==============================] - ETA: 0s - loss: 0.4790
Epoch 6: loss improved from 0.48254 to 0.47900, saving model to best_model.h5
201/201 [==============================] - 66s 330ms/step - loss: 0.4790
Epoch 7/500
201/201 [==============================] - ETA: 0s - loss: 0.4913
Epoch 7: loss did not improve from 0.47900
201/201 [==============================] - 66s 328ms/step - loss: 0.4913
Epoch 8/500
201/201 [==============================] - ETA: 0s - loss: 0.4856
Epoch 8: loss did not improve from 0.47900
201/201 [==============================] - 66s 328ms/step - loss: 0.4856
Epoch 9/500
201/201 [==============================] - ETA: 0s - loss: 0.4951
Epoch 9: loss did not improve from 0.47900
201/201 [==============================] - 66s 329ms/step - loss: 0.4951
Epoch 10/500
201/201 [==============================] - ETA: 0s - loss: 0.4757
Epoch 10: loss improved from 0.47900 to 0.47565, saving model to best_model.h5
201/201 [==============================] - 66s 329ms/step - loss: 0.4757
Epoch 11/500
201/201 [==============================] - ETA: 0s - loss: 0.5056
Epoch 11: loss did not improve from 0.47565
201/201 [==============================] - 65s 325ms/step - loss: 0.5056
Epoch 12/500
201/201 [==============================] - ETA: 0s - loss: 0.4979
Epoch 12: loss did not improve from 0.47565
201/201 [==============================] - 84s 417ms/step - loss: 0.4979
Epoch 13/500
201/201 [==============================] - ETA: 0s - loss: 0.4954
Epoch 13: loss did not improve from 0.47565
201/201 [==============================] - 66s 326ms/step - loss: 0.4954
Epoch 14/500
201/201 [==============================] - ETA: 0s - loss: 0.4833
Epoch 14: loss did not improve from 0.47565
201/201 [==============================] - 67s 331ms/step - loss: 0.4833
Epoch 15/500
201/201 [==============================] - ETA: 0s - loss: 0.4927
Epoch 15: loss did not improve from 0.47565
201/201 [==============================] - 67s 333ms/step - loss: 0.4927
Epoch 16/500
201/201 [==============================] - ETA: 0s - loss: 0.4797
Epoch 16: loss did not improve from 0.47565
201/201 [==============================] - 66s 326ms/step - loss: 0.4797
Epoch 17/500
201/201 [==============================] - ETA: 0s - loss: 0.4871
Epoch 17: loss did not improve from 0.47565
201/201 [==============================] - 65s 325ms/step - loss: 0.4871
Epoch 18/500
201/201 [==============================] - ETA: 0s - loss: 0.4774
Epoch 18: loss did not improve from 0.47565
201/201 [==============================] - 65s 325ms/step - loss: 0.4774
Epoch 19/500
201/201 [==============================] - ETA: 0s - loss: 0.4714
Epoch 19: loss improved from 0.47565 to 0.47138, saving model to best_model.h5
201/201 [==============================] - 66s 326ms/step - loss: 0.4714
Epoch 20/500
201/201 [==============================] - ETA: 0s - loss: 0.4890
Epoch 20: loss did not improve from 0.47138
201/201 [==============================] - 65s 325ms/step - loss: 0.4890
Epoch 21/500
201/201 [==============================] - ETA: 0s - loss: 0.4784
Epoch 21: loss did not improve from 0.47138
201/201 [==============================] - 66s 327ms/step - loss: 0.4784
Epoch 22/500
201/201 [==============================] - ETA: 0s - loss: 0.4905
Epoch 22: loss did not improve from 0.47138
201/201 [==============================] - 66s 330ms/step - loss: 0.4905
Epoch 23/500
201/201 [==============================] - ETA: 0s - loss: 0.4666
Epoch 23: loss improved from 0.47138 to 0.46661, saving model to best_model.h5
201/201 [==============================] - 64s 320ms/step - loss: 0.4666
Epoch 24/500
201/201 [==============================] - ETA: 0s - loss: 0.4778
Epoch 24: loss did not improve from 0.46661
201/201 [==============================] - 66s 327ms/step - loss: 0.4778
Epoch 25/500
201/201 [==============================] - ETA: 0s - loss: 0.4802
Epoch 25: loss did not improve from 0.46661
201/201 [==============================] - 65s 324ms/step - loss: 0.4802
Epoch 26/500
201/201 [==============================] - ETA: 0s - loss: 0.4645
Epoch 26: loss improved from 0.46661 to 0.46445, saving model to best_model.h5
201/201 [==============================] - 66s 328ms/step - loss: 0.4645
Epoch 27/500
201/201 [==============================] - ETA: 0s - loss: 0.4732
Epoch 27: loss did not improve from 0.46445
201/201 [==============================] - 66s 328ms/step - loss: 0.4732
Epoch 28/500
201/201 [==============================] - ETA: 0s - loss: 0.4617
Epoch 28: loss improved from 0.46445 to 0.46171, saving model to best_model.h5
201/201 [==============================] - 66s 326ms/step - loss: 0.4617
Epoch 29/500
201/201 [==============================] - ETA: 0s - loss: 0.4633
Epoch 29: loss did not improve from 0.46171
201/201 [==============================] - 66s 326ms/step - loss: 0.4633
Epoch 30/500
201/201 [==============================] - ETA: 0s - loss: 0.4751
Epoch 30: loss did not improve from 0.46171
201/201 [==============================] - 66s 328ms/step - loss: 0.4751
Epoch 31/500
201/201 [==============================] - ETA: 0s - loss: 0.4648
Epoch 31: loss did not improve from 0.46171
201/201 [==============================] - 65s 324ms/step - loss: 0.4648
Epoch 32/500
201/201 [==============================] - ETA: 0s - loss: 0.4738
Epoch 32: loss did not improve from 0.46171
201/201 [==============================] - 67s 335ms/step - loss: 0.4738
Epoch 33/500
201/201 [==============================] - ETA: 0s - loss: 0.4556
Epoch 33: loss improved from 0.46171 to 0.45558, saving model to best_model.h5
201/201 [==============================] - 67s 333ms/step - loss: 0.4556
Epoch 34/500
201/201 [==============================] - ETA: 0s - loss: 0.4488
Epoch 34: loss improved from 0.45558 to 0.44883, saving model to best_model.h5
201/201 [==============================] - 66s 326ms/step - loss: 0.4488
Epoch 35/500
201/201 [==============================] - ETA: 0s - loss: 0.4606
Epoch 35: loss did not improve from 0.44883
201/201 [==============================] - 67s 331ms/step - loss: 0.4606
Epoch 36/500
201/201 [==============================] - ETA: 0s - loss: 0.4613
Epoch 36: loss did not improve from 0.44883
201/201 [==============================] - 67s 335ms/step - loss: 0.4613
Epoch 37/500
201/201 [==============================] - ETA: 0s - loss: 0.4527
Epoch 37: loss did not improve from 0.44883
201/201 [==============================] - 67s 332ms/step - loss: 0.4527
Epoch 38/500
201/201 [==============================] - ETA: 0s - loss: 0.4430
Epoch 38: loss improved from 0.44883 to 0.44302, saving model to best_model.h5
201/201 [==============================] - 66s 327ms/step - loss: 0.4430
Epoch 39/500
201/201 [==============================] - ETA: 0s - loss: 0.4684
Epoch 39: loss did not improve from 0.44302
201/201 [==============================] - 65s 325ms/step - loss: 0.4684
Epoch 40/500
201/201 [==============================] - ETA: 0s - loss: 0.4523
Epoch 40: loss did not improve from 0.44302
201/201 [==============================] - 66s 326ms/step - loss: 0.4523
Epoch 41/500
201/201 [==============================] - ETA: 0s - loss: 0.4497
Epoch 41: loss did not improve from 0.44302
201/201 [==============================] - 67s 335ms/step - loss: 0.4497
Epoch 42/500
201/201 [==============================] - ETA: 0s - loss: 0.4408
Epoch 42: loss improved from 0.44302 to 0.44084, saving model to best_model.h5
201/201 [==============================] - 66s 329ms/step - loss: 0.4408
Epoch 43/500
201/201 [==============================] - ETA: 0s - loss: 0.4486
Epoch 43: loss did not improve from 0.44084
201/201 [==============================] - 65s 325ms/step - loss: 0.4486
Epoch 44/500
201/201 [==============================] - ETA: 0s - loss: 0.4515
Epoch 44: loss did not improve from 0.44084
201/201 [==============================] - 65s 324ms/step - loss: 0.4515
Epoch 45/500
201/201 [==============================] - ETA: 0s - loss: 0.4452
Epoch 45: loss did not improve from 0.44084
201/201 [==============================] - 66s 326ms/step - loss: 0.4452
Epoch 46/500
201/201 [==============================] - ETA: 0s - loss: 0.4408
Epoch 46: loss improved from 0.44084 to 0.44082, saving model to best_model.h5
201/201 [==============================] - 66s 326ms/step - loss: 0.4408
Epoch 47/500
201/201 [==============================] - ETA: 0s - loss: 0.4504
Epoch 47: loss did not improve from 0.44082
201/201 [==============================] - 65s 324ms/step - loss: 0.4504
Epoch 48/500
201/201 [==============================] - ETA: 0s - loss: 0.4430
Epoch 48: loss did not improve from 0.44082
201/201 [==============================] - 65s 325ms/step - loss: 0.4430
Epoch 49/500
201/201 [==============================] - ETA: 0s - loss: 0.4496
Epoch 49: loss did not improve from 0.44082
201/201 [==============================] - 66s 328ms/step - loss: 0.4496
Epoch 50/500
201/201 [==============================] - ETA: 0s - loss: 0.4414
Epoch 50: loss did not improve from 0.44082
201/201 [==============================] - 66s 328ms/step - loss: 0.4414
Epoch 51/500
201/201 [==============================] - ETA: 0s - loss: 0.4426
Epoch 51: loss did not improve from 0.44082
201/201 [==============================] - 66s 327ms/step - loss: 0.4426
Epoch 52/500
201/201 [==============================] - ETA: 0s - loss: 0.4411
Epoch 52: loss did not improve from 0.44082
201/201 [==============================] - 65s 324ms/step - loss: 0.4411
Epoch 53/500
201/201 [==============================] - ETA: 0s - loss: 0.4359
Epoch 53: loss improved from 0.44082 to 0.43587, saving model to best_model.h5
201/201 [==============================] - 66s 326ms/step - loss: 0.4359
Epoch 54/500
201/201 [==============================] - ETA: 0s - loss: 0.4395
Epoch 54: loss did not improve from 0.43587
201/201 [==============================] - 66s 328ms/step - loss: 0.4395
Epoch 55/500
201/201 [==============================] - ETA: 0s - loss: 0.4437
Epoch 55: loss did not improve from 0.43587
201/201 [==============================] - 66s 327ms/step - loss: 0.4437
Epoch 56/500
201/201 [==============================] - ETA: 0s - loss: 0.4428
Epoch 56: loss did not improve from 0.43587
201/201 [==============================] - 66s 326ms/step - loss: 0.4428
Epoch 57/500
201/201 [==============================] - ETA: 0s - loss: 0.4399
Epoch 57: loss did not improve from 0.43587
201/201 [==============================] - 66s 330ms/step - loss: 0.4399
Epoch 58/500
201/201 [==============================] - ETA: 0s - loss: 0.4377
Epoch 58: loss did not improve from 0.43587
201/201 [==============================] - 66s 328ms/step - loss: 0.4377
Epoch 59/500
201/201 [==============================] - ETA: 0s - loss: 0.4379
Epoch 59: loss did not improve from 0.43587
201/201 [==============================] - 65s 324ms/step - loss: 0.4379
Epoch 60/500
201/201 [==============================] - ETA: 0s - loss: 0.4331
Epoch 60: loss improved from 0.43587 to 0.43306, saving model to best_model.h5
201/201 [==============================] - 66s 329ms/step - loss: 0.4331
Epoch 61/500
201/201 [==============================] - ETA: 0s - loss: 0.4359
Epoch 61: loss did not improve from 0.43306
201/201 [==============================] - 65s 325ms/step - loss: 0.4359
Epoch 62/500
201/201 [==============================] - ETA: 0s - loss: 0.4323
Epoch 62: loss improved from 0.43306 to 0.43226, saving model to best_model.h5
201/201 [==============================] - 65s 323ms/step - loss: 0.4323
Epoch 63/500
201/201 [==============================] - ETA: 0s - loss: 0.4341
Epoch 63: loss did not improve from 0.43226
201/201 [==============================] - 65s 324ms/step - loss: 0.4341
Epoch 64/500
201/201 [==============================] - ETA: 0s - loss: 0.4345
Epoch 64: loss did not improve from 0.43226
201/201 [==============================] - 66s 328ms/step - loss: 0.4345
Epoch 65/500
201/201 [==============================] - ETA: 0s - loss: 0.4326
Epoch 65: loss did not improve from 0.43226
201/201 [==============================] - 66s 328ms/step - loss: 0.4326
Epoch 66/500
201/201 [==============================] - ETA: 0s - loss: 0.4332
Epoch 66: loss did not improve from 0.43226
201/201 [==============================] - 65s 324ms/step - loss: 0.4332
Epoch 67/500
201/201 [==============================] - ETA: 0s - loss: 0.4241
Epoch 67: loss improved from 0.43226 to 0.42410, saving model to best_model.h5
201/201 [==============================] - 66s 329ms/step - loss: 0.4241
Epoch 68/500
201/201 [==============================] - ETA: 0s - loss: 0.4304
Epoch 68: loss did not improve from 0.42410
201/201 [==============================] - 66s 330ms/step - loss: 0.4304
Epoch 69/500
201/201 [==============================] - ETA: 0s - loss: 0.4255
Epoch 69: loss did not improve from 0.42410
201/201 [==============================] - 66s 328ms/step - loss: 0.4255
Epoch 70/500
201/201 [==============================] - ETA: 0s - loss: 0.4279
Epoch 70: loss did not improve from 0.42410
201/201 [==============================] - 66s 328ms/step - loss: 0.4279
Epoch 71/500
201/201 [==============================] - ETA: 0s - loss: 0.4207
Epoch 71: loss improved from 0.42410 to 0.42069, saving model to best_model.h5
201/201 [==============================] - 66s 329ms/step - loss: 0.4207
Epoch 72/500
201/201 [==============================] - ETA: 0s - loss: 0.4196
Epoch 72: loss improved from 0.42069 to 0.41958, saving model to best_model.h5
201/201 [==============================] - 66s 327ms/step - loss: 0.4196
Epoch 73/500
201/201 [==============================] - ETA: 0s - loss: 0.4273
Epoch 73: loss did not improve from 0.41958
201/201 [==============================] - 66s 330ms/step - loss: 0.4273
Epoch 74/500
201/201 [==============================] - ETA: 0s - loss: 0.4217
Epoch 74: loss did not improve from 0.41958
201/201 [==============================] - 65s 326ms/step - loss: 0.4217
Epoch 75/500
201/201 [==============================] - ETA: 0s - loss: 0.4194
Epoch 75: loss improved from 0.41958 to 0.41939, saving model to best_model.h5
201/201 [==============================] - 66s 326ms/step - loss: 0.4194
Epoch 76/500
201/201 [==============================] - ETA: 0s - loss: 0.4128
Epoch 76: loss improved from 0.41939 to 0.41284, saving model to best_model.h5
201/201 [==============================] - 66s 327ms/step - loss: 0.4128
Epoch 77/500
201/201 [==============================] - ETA: 0s - loss: 0.4118
Epoch 77: loss improved from 0.41284 to 0.41176, saving model to best_model.h5
201/201 [==============================] - 66s 330ms/step - loss: 0.4118
Epoch 78/500
201/201 [==============================] - ETA: 0s - loss: 0.4123
Epoch 78: loss did not improve from 0.41176
201/201 [==============================] - 65s 325ms/step - loss: 0.4123
Epoch 79/500
201/201 [==============================] - ETA: 0s - loss: 0.4194
Epoch 79: loss did not improve from 0.41176
201/201 [==============================] - 66s 328ms/step - loss: 0.4194
Epoch 80/500
201/201 [==============================] - ETA: 0s - loss: 0.4095
Epoch 80: loss improved from 0.41176 to 0.40950, saving model to best_model.h5
201/201 [==============================] - 66s 330ms/step - loss: 0.4095
Epoch 81/500
201/201 [==============================] - ETA: 0s - loss: 0.4007
Epoch 81: loss improved from 0.40950 to 0.40073, saving model to best_model.h5
201/201 [==============================] - 65s 326ms/step - loss: 0.4007
Epoch 82/500
201/201 [==============================] - ETA: 0s - loss: 0.4028
Epoch 82: loss did not improve from 0.40073
201/201 [==============================] - 66s 328ms/step - loss: 0.4028
Epoch 83/500
201/201 [==============================] - ETA: 0s - loss: 0.4021
Epoch 83: loss did not improve from 0.40073
201/201 [==============================] - 65s 324ms/step - loss: 0.4021
Epoch 84/500
201/201 [==============================] - ETA: 0s - loss: 0.4035
Epoch 84: loss did not improve from 0.40073
201/201 [==============================] - 66s 328ms/step - loss: 0.4035
Epoch 85/500
201/201 [==============================] - ETA: 0s - loss: 0.3969
Epoch 85: loss improved from 0.40073 to 0.39687, saving model to best_model.h5
201/201 [==============================] - 66s 327ms/step - loss: 0.3969
Epoch 86/500
201/201 [==============================] - ETA: 0s - loss: 0.3959
Epoch 86: loss improved from 0.39687 to 0.39592, saving model to best_model.h5
201/201 [==============================] - 66s 330ms/step - loss: 0.3959
Epoch 87/500
201/201 [==============================] - ETA: 0s - loss: 0.3955
Epoch 87: loss improved from 0.39592 to 0.39553, saving model to best_model.h5
201/201 [==============================] - 66s 327ms/step - loss: 0.3955
Epoch 88/500
201/201 [==============================] - ETA: 0s - loss: 0.3932
Epoch 88: loss improved from 0.39553 to 0.39323, saving model to best_model.h5
201/201 [==============================] - 66s 327ms/step - loss: 0.3932
Epoch 89/500
201/201 [==============================] - ETA: 0s - loss: 0.4007
Epoch 89: loss did not improve from 0.39323
201/201 [==============================] - 65s 324ms/step - loss: 0.4007
Epoch 90/500
201/201 [==============================] - ETA: 0s - loss: 0.3870
Epoch 90: loss improved from 0.39323 to 0.38698, saving model to best_model.h5
201/201 [==============================] - 66s 329ms/step - loss: 0.3870
Epoch 91/500
201/201 [==============================] - ETA: 0s - loss: 0.3894
Epoch 91: loss did not improve from 0.38698
201/201 [==============================] - 66s 330ms/step - loss: 0.3894
Epoch 92/500
201/201 [==============================] - ETA: 0s - loss: 0.3850
Epoch 92: loss improved from 0.38698 to 0.38503, saving model to best_model.h5
201/201 [==============================] - 66s 329ms/step - loss: 0.3850
Epoch 93/500
201/201 [==============================] - ETA: 0s - loss: 0.3855
Epoch 93: loss did not improve from 0.38503
201/201 [==============================] - 66s 328ms/step - loss: 0.3855
Epoch 94/500
201/201 [==============================] - ETA: 0s - loss: 0.3849
Epoch 94: loss improved from 0.38503 to 0.38492, saving model to best_model.h5
201/201 [==============================] - 67s 332ms/step - loss: 0.3849
Epoch 95/500
201/201 [==============================] - ETA: 0s - loss: 0.3836
Epoch 95: loss improved from 0.38492 to 0.38364, saving model to best_model.h5
201/201 [==============================] - 66s 328ms/step - loss: 0.3836
Epoch 96/500
201/201 [==============================] - ETA: 0s - loss: 0.3768
Epoch 96: loss improved from 0.38364 to 0.37678, saving model to best_model.h5

KeyboardInterrupt: ignored

In [ ]:
from keras.models import load_model
saved_model = load_model('best_model.h5')
y_pred = saved_model.predict(X_test)
from sklearn.metrics import mean_squared_error
errors = mean_squared_error(y_test, y_pred)

print(errors)

0.6953495538612248